spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/transfer_query
    password: postgres
    username: postgres
    properties:
      sslMode: DISABLE
      prepareThreshold: 0
      preparedStatementCacheQueries: 0
      lock_wait_timeout: 1s

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transfer-query
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  flyway:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transfer_query
    user: postgres
    password: postgres

inbox:
  aggregate:
    TRANSFER:
      batch-size: 40

server:
  port: 2222
