version: "3"

services:
  postgres:
    container_name: pg_pg
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - /tmp/mount:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  zookeeper:
    container_name: zk_zk
    image: confluentinc/cp-zookeeper:5.4.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - default
  
  kafka:
    container_name: kfk_kfk
    image: confluentinc/cp-kafka:5.4.9
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default

  service:
    container_name: query_srv
#    image: query-service:1.0.0
    image: query:0.0.1-SNAPSHOT
    depends_on:
      - postgres
    ports:
      - "2222:2222"
    networks:
      - default


networks:
  default:
    driver: bridge